{% set name = "comm" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2dc8048c10962d55d7ad693be1e7045d891b7ce8d999c97963a5e3e99c055971

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py<38]

requirements:
  host:
    - python
    - pip
    - hatchling >=1.10
  run:
    - python
    - traitlets >=4

test:
  imports:
    - comm
    - comm.base_comm
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/ipython/comm
  summary: Python Comm implementation for the Jupyter kernel protocol
  description: Python Comm implementation for the Jupyter kernel protocol
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://github.com/ipython/comm/blob/main/README.md
  dev_url: https://github.com/ipython/comm

extra:
  recipe-maintainers:
    - martinRenou
