{% set name = "comm" %}
{% set version = "0.2.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/ipython/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6db2cd1b5ab7ff52c6fe8df473d5518b29fe5f0e5ec267fc731272a71e46a5ea

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<38]

requirements:
  host:
    - pip
    - python
    - hatchling >=1.10
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - comm
    - comm.base_comm
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/ipython/comm
  summary: Python Comm implementation for the Jupyter kernel protocol
  description: Python Comm implementation for the Jupyter kernel protocol
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://github.com/ipython/comm/blob/main/README.md
  dev_url: https://github.com/ipython/comm

extra:
  recipe-maintainers:
    - martinRenou
